apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatling-server.fullname" . }}
  labels:
    {{- include "gatling-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gatling-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gatling-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gatling-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "gatling-server.secretName" . }}
                  key: API_TOKEN
            - name: BROWSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "gatling-server.secretName" . }}
                  key: BROWSE_USERNAME
            - name: BROWSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gatling-server.secretName" . }}
                  key: BROWSE_PASSWORD
          ports:
            - name: http
              containerPort: 58080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /probe/live
              port: http
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/workspace
              subPath: workspace
            - name: data
              mountPath: /app/uploads
              subPath: uploads
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "gatling-server.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
