{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatling-server.fullname" . }}
  labels:
    {{- include "gatling-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.apiToken | quote }}
  BROWSE_USERNAME: {{ .Values.browseUsername | quote }}
  BROWSE_PASSWORD: {{ .Values.browsePassword | quote }}
{{- end }}
